language: python

python:
  - "3.6"

before_install:
  - mkdir $TRAVIS_BUILD_DIR/root
  - export POGETHER_ROOT=$TRAVIS_BUILD_DIR/root/
  - pip3 install -r requirements.txt


install:  
  - cd src
  - python3 manage.py makemigrations core
  - python3 manage.py migrate


script: 
  - python3 manage.py test

